version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - C:\Users\dell\node-app\src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env
